//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2015 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

/* ------------- Structures ------------- */

struct _struct__IO_FILE {
    int32_t e0;
    char * e1;
    char * e2;
    char * e3;
    char * e4;
    char * e5;
    char * e6;
    char * e7;
    char * e8;
    char * e9;
    char * e10;
    char * e11;
    struct _struct__IO_marker * e12;
    struct _struct__IO_FILE * e13;
    int32_t e14;
    int32_t e15;
    int32_t e16;
    int16_t e17;
    char e18;
    int32_t e19[1];
    char * e20;
    int64_t e21;
    char * e22;
    char * e23;
    char * e24;
    char * e25;
    int32_t e26;
    int32_t e27;
    int32_t e28[40];
};

struct _struct__IO_marker {
    struct _struct__IO_marker * e0;
    struct _struct__IO_FILE * e1;
    int32_t e2;
};

struct struct_0 {
    int32_t * e0;
    int32_t e1;
    int32_t * e2;
};

/* -------- Function Prototypes --------- */

int32_t get_password(void);

/* ---------- Global Variables ---------- */

int32_t g1 = 0; // 0x804a044
bool valid = false; // zf0

/* ------------- Functions -------------- */

// Address range: 0x804864d - 0x80486ed
int32_t get_password(void) {
    // 0x804864d
    valid = false;
    struct _struct__IO_FILE * file = fopen("flag.txt", "r"); // 0x8048662
    fseek(file, 0, SEEK_END);
    struct _struct__IO_FILE * curr_file_offset = (struct _struct__IO_FILE *)ftell(file); // bp-20
    fseek(file, 0, SEEK_SET);
    int32_t * mem = malloc((int32_t)curr_file_offset); // 0x80486b4
    int32_t * v1 = mem; // bp-36
    fscanf(file, "%s", &v1);
    puts((char *)mem);
    free(mem);
    return (int32_t)mem;
}

// Address range: 0x80486ee - 0x8048bae
int main(int argc, char ** argv) {
    struct struct_0 * v1 = NULL; // bp-364
    puts("You stumble into Mirkwood Forest without a map.");
    puts("Without any sense of direction you look around in despair as you remember these woods are littered with the unforgiving Wood Elves and giant spiders.");
    puts("You begin to try different paths in hopes that one of them will lead you out of the woods.");
    char * str;
    fgets(str, 64, (struct _struct__IO_FILE *)g1);
    struct struct_0 * v2 = v1; // 0x8048a96_0
    struct struct_0 * v3 = v2; // 0x8048ae2_0
    int32_t counter = 0;
    int32_t v5 = v2->e1; // 0x8048b5d12
    // branch -> 0x8048aae
    int32_t score;
    while (true) {
        // 0x8048aae
        int32_t v7; // 0x8048b39
        struct struct_0 * v8; // 0x8048b2e_0
        int32_t v9; // 0x8048b35
        if (str != "L") {
            // 0x8048ace
            struct struct_0 * v10; // 0x8048b17_0
            if (str == "R") {
                int32_t * v11 = v3->e2; // 0x8048ae6
                v1 = (struct struct_0 *)v11;
                v10 = (struct struct_0 *)v11;
                // branch -> 0x8048b17
lab_0x2973e70:
                // 0x8048b17
                printf("You found a: %x!\n", v10->e1);
                v8 = v1;
                v9 = v8->e1 ^ v5;
                v7 = counter + 1;
                if (v7 >= 64) {
                    score = v9;
                    // break -> 0x8048b49
                    break;
                }
                v3 = v8;
                counter = v7;
                v5 = v9;
                // continue -> 0x8048aae
                continue;
            } else {
                // 0x8048aef
                if (str != NULL) {
                    // 0x8048b03
                    // Quit
                    if (str != "\n") {
                        v10 = v3;
                        goto lab_0x2973e70;
                    }
                    score = v5;
                    // 0x8048b49
                    printf("At the end of your journey, your value became: %d\n", score);
                    valid = score == 1984717964;
                    if (score == 1984717964) {
                        // 0x8048b67
                        puts("You made it out alive!");
                        get_password();
                        // branch -> 0x8048b92
                    } else {
                        // 0x8048b7a
                        puts("You were eaten by spiders :c");
                        puts("Game Over");
                        // branch -> 0x8048b92
                    }
                    // 0x8048b92
                    if (!valid) {
                        // 0x8048ba7
                        __stack_chk_fail();
                        // branch -> 0x8048bac
                    }
                    // 0x8048bac
                    return 0;
                }
                score = v5;
            }
            // 0x8048b49
            printf("At the end of your journey, your value became: %d\n", score);
            valid = score == 1984717964;
            if (score == 1984717964) {
                // 0x8048b67
                puts("You made it out alive!");
                get_password();
                // branch -> 0x8048b92
            } else {
                // 0x8048b7a
                puts("You were eaten by spiders :c");
                puts("Game Over");
                // branch -> 0x8048b92
            }
            // 0x8048b92
            if (!valid) {
                // 0x8048ba7
                __stack_chk_fail();
                // branch -> 0x8048bac
            }
            // 0x8048bac
            return 0;
        }
        struct struct_0 * v12 = (struct struct_0 *)*(int32_t *)v3; // 0x8048ac8_0
        v1 = v12;
        // branch -> 0x8048b17
        // 0x8048b17
        printf("You found a: %x!\n", v12->e1);
        v8 = v1;
        v9 = v8->e1 ^ v5;
        v7 = counter + 1;
        if (v7 >= 64) {
            score = v9;
            // break -> 0x8048b49
            break;
        }
        v3 = v8;
        counter = v7;
        v5 = v9;
        // continue -> 0x8048aae
    }
    // 0x8048b49
    printf("At the end of your journey, your value became: %d\n", score);
    valid = score == 1984717964;
    if (score == 1984717964) {
        // 0x8048b67
        puts("You made it out alive!");
        get_password();
        // branch -> 0x8048b92
    } else {
        // 0x8048b7a
        puts("You were eaten by spiders :c");
        puts("Game Over");
        // branch -> 0x8048b92
    }
    // 0x8048b92
    if (!valid) {
        // 0x8048ba7
        __stack_chk_fail();
        // branch -> 0x8048bac
    }
    // 0x8048bac
    return 0;
}

/* --------- External Functions --------- */

// void __stack_chk_fail(void);
// char * fgets (char *restrict, int, FILE *restrict)
// FILE * fopen (const char *restrict, const char *restrict)
// void free (void *)
// int fscanf (FILE *restrict, const char *restrict, ...)
// int fseek (FILE *, long, int)
// long ftell (FILE *)
// void * malloc (size_t)
// int printf (const char *restrict, ...)
// int puts (const char *)

/* ---------- Meta-Information ---------- */

// Detected compiler: gcc 4.8.4
// Detected functions: 2 (2 in front-end)
// Decompiler release: v2.0 (Jun  1 2015)
// Decompilation date: Oct 05 2015 00:53:37
